### ISSUE TITLE
Golang support 

### ISSUE THREAD

**Issue by gedw99** [wasmCloud/interfaces#134]
Is golang still supported ?

**Comment by brooksmtownsend** [comment]
Hey @gedw99, we do still have support for [TinyGo](https://tinygo.org/) actors using the interfaces in this repository. You can see an example in [kvcounter-tinygo](https://github.com/wasmCloud/examples/tree/main/actor/kvcounter-tinygo) for something that uses two of our standard interfaces for http and keyvalue!
