### ISSUE TITLE
Logging interface macros should suppress failures

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/interfaces#40]
Right now the logging interface macros all use `?.await` (e.g. the `debug!`, `info!`, etc). This forces these macros to only be usable inside a function that returns a Result/RpcResult. Rather than enforcing this, the macros should gracefully do nothing if logging attempts fail (because, after all, what other recourse does an actor have if logging fails? It can't log the failure...). 

This lets developers use these macros in functions that don't return results.

**Comment by stevelr** [comment]
Disagree. We should add new functions that surprise errors.
The caller should make the choice about whether to surprises errors and the default library behavior should return errors.

**Comment by autodidaddict** [comment]
I think the inverse should be true. If I use `debug!` from the `log` crate, I do not have to do so from within a Result-returning function, so as a developer I would expect the same to be true when using wasmCloud's logging macro. If we want macros that _do not_ suppress errors, then we should use differently named ones so that developers can predict how things are going to behave.

So, proposal:
* `debug!` (and others) - suppress failure
* `debug_result!` (or whatever we want to call it) - this is where the `?` should be left.

**Comment by stevelr** [comment]
For the record, even if the implementation is changed to suppress errors, it won't be api compatible with the `log` crate, because interface/logging macros use `.await` and so must be inside an async block.
