### ISSUE TITLE
Remove async from Rust wasm32 interfaces

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/interfaces#42]
Part of the value proposition of the actor model, and by extension wasmCloud, is that actors are all internally _synchronous_. They are single-threaded and developers don't have to worry about writing asynchronous code. Unfortunately, because Rust makes it a little _too_ easy to compile certain things inside wasm32, it was pretty easy to make the generated code produce `async` stuff that can be used by either side of the provider/actor exchange.

What I'd like to see is that anything that an actor might use from the generated output be purely synchronous without any use of the `async` keyword. It should still be possible to allow the capability providers to utilize an async version of the trait with conditional compilation.

I suspect that in the absence of `async`, the process of building actors will be simpler, faster, and easier to learn for newer Rust developers. Further, I also suspect that without having to compile a single-threaded executor like tokio into the wasm module will reduce the overall actor size as well.

**Comment by stevelr** [comment]
Not a simple change, and has some pros & cons. I'll collect some notes to post later.

For the record, there is no tokio executor compiled into actor wasm files. The executor is a single-threaded executor from `futures::executor`, which, according to the `twiggy` utility, uses about 0.01% of the wasm code size.
